# Generated by Django 6.1.1 on 2026-09-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
